
name = "shilll"
compatibility_date = "2024-07-31"

type = "webpack" # or "javascript" depending on your setup

[build]
command = "npm run build"

[site]
bucket = "./build/client"  # your build output folder
entry-point = "."          # leave as "." unless you use Workers functions
